# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
first_name: Abde Manaaf
middle_name: Z.
last_name: Ghadiali
email: abdemanaaf.ghadiali.1998@gmail.com
github_username: default741

contact_note: >
  The most effective way to contact me is via email.
description: >
  A personal portfolio and blog featuring a downloadable resume, GitHub repositories, and a bookshelf section showcasing books I have read, along with summaries and my personal insights.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

lang: en
icon: site_icon.png

url: https://default741.github.io/
baseurl: ""
last_updated: true
back_to_top: true

keywords: abdemanaaf-ghadiali, academic-website, portfolio-website, quantum-computing, machine-learning, gwu, george-washington-university

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

rss_icon: true
navbar_fixed: false
footer_fixed: false
max_width: 940px

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: how-to-be-boring
blog_description: >
  A collection of technical articles on Quantum Computing, Machine Learning, and Data Science, along with key academic textbook chapters essential for both graduate and undergraduate studies.
  Additionally, the section includes reviews and summaries of important research papers and articles.
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

external_sources:
  - name: medium.com
    rss_url: https://medium.com/@abdemanaaf.ghadiali.1998/demystifying-the-quantum-part-1-a-dive-into-qubits-and-beyond-79eba5e239a6

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - vendor
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed
  - jekyll-get-json
  - jekyll-toc
  - jekyll-link-attributes
  - fiddle
  - faraday-retry

defaults:
- scope:
    path: "assets"
  values:
    sitemap: false

sass:
  sass_dir: _sass
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:


# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_darkmode: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      css_map: "sha256-iYYMNfsJdVZjvsebJulg09miBXM4/GMTJgv1u5EZFFM="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
      js_map: "sha256-UPgyn4YNsT0khkBK5553QwhnlbTlU0aa+igyc6qP1bE="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css"
      css_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css.map"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js.map"
    version: "4.20.0"
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js"
    version: "3.6.0"

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - skills
  - education
  - certificates
  - awards
  - interests
  - volunteer
  - languages
  - references
