# Site Settings
title: blank
first_name: Abde Manaaf
middle_name: Z.
last_name: Ghadiali
email: abdemanaaf.ghadiali.1998@gmail.com

description: >
  Personal Portfolio and Blog.

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

baseurl: ""
url: "https://default741.github.io/"

github_username: default741

# Build Settings
sass:
  sass_dir: _sass

include: ["_pages"]

kramdown:
  input: GFM
